apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"orphan-ing","namespace":"krkn-ps-fixture"},"spec":{"ingressClassName":"nonexistent","rules":[{"host":"orphan.test.local","http":{"paths":[{"backend":{"service":{"name":"web-svc","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    creationTimestamp: "2026-05-12T07:18:06Z"
    generation: 1
    name: orphan-ing
    namespace: krkn-ps-fixture
    resourceVersion: "812"
    uid: 2d204871-d029-4568-9425-655f10211bb6
  spec:
    ingressClassName: nonexistent
    rules:
    - host: orphan.test.local
      http:
        paths:
        - backend:
            service:
              name: web-svc
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"web-ing","namespace":"krkn-ps-fixture"},"spec":{"ingressClassName":"nginx","rules":[{"host":"web.test.local","http":{"paths":[{"backend":{"service":{"name":"web-svc","port":{"number":80}}},"path":"/","pathType":"Prefix"},{"backend":{"service":{"name":"web-svc","port":{"number":80}}},"path":"/healthz/notfound","pathType":"Exact"}]}}]}}
    creationTimestamp: "2026-05-12T07:18:06Z"
    generation: 1
    name: web-ing
    namespace: krkn-ps-fixture
    resourceVersion: "945"
    uid: 789720f1-bd7c-44a7-bc54-a30dc29e9885
  spec:
    ingressClassName: nginx
    rules:
    - host: web.test.local
      http:
        paths:
        - backend:
            service:
              name: web-svc
              port:
                number: 80
          path: /
          pathType: Prefix
        - backend:
            service:
              name: web-svc
              port:
                number: 80
          path: /healthz/notfound
          pathType: Exact
  status:
    loadBalancer:
      ingress:
      - hostname: localhost
kind: List
metadata:
  resourceVersion: ""
