#!/usr/bin/env bash
# capture-openshift-cluster.sh - capture OpenShift metadata + current discover output.
#
# Usage:
#   bash _local/LFX/fixtures/capture-openshift-cluster.sh <run-id> [kubeconfig]
set -euo pipefail

if [[ "$#" -lt 1 || "$#" -gt 2 ]]; then
  echo "Usage: $0 <run-id> [kubeconfig]"
  exit 1
fi

RUN_ID="$1"
KUBECONFIG_PATH="${2:-${KUBECONFIG:-$HOME/.kube/config}}"
RUN_DIR="_local/LFX/real-cluster-runs/${RUN_ID}"

mkdir -p "$RUN_DIR"/cluster "$RUN_DIR"/generated "$RUN_DIR"/analysis

if [[ -f "$KUBECONFIG_PATH" ]]; then
  export KUBECONFIG="$KUBECONFIG_PATH"
fi

oc version > "$RUN_DIR/cluster/version.txt"
oc whoami > "$RUN_DIR/cluster/whoami.txt"
oc config current-context > "$RUN_DIR/cluster/context.txt"

oc get clusterversion -o yaml > "$RUN_DIR/cluster/clusterversion.yaml" 2>&1 || true
oc get namespaces > "$RUN_DIR/cluster/namespaces.txt"
oc get pods -n krkn-ps-fixture -o wide > "$RUN_DIR/cluster/pods-wide.txt"
oc get svc -n krkn-ps-fixture -o wide > "$RUN_DIR/cluster/services-wide.txt"
oc get route -n krkn-ps-fixture -o wide > "$RUN_DIR/cluster/routes-wide.txt"
oc get pvc -n krkn-ps-fixture > "$RUN_DIR/cluster/pvc.txt"
oc get nodes -o wide > "$RUN_DIR/cluster/nodes-wide.txt"

oc get svc -n krkn-ps-fixture -o yaml > "$RUN_DIR/cluster/services-full.yaml"
oc get route -n krkn-ps-fixture -o yaml > "$RUN_DIR/cluster/routes-full.yaml"
oc get route -n openshift-monitoring -o yaml > "$RUN_DIR/cluster/openshift-monitoring-routes.yaml" 2>&1 || true
oc get prometheus -A -o yaml > "$RUN_DIR/cluster/prometheus-crd.yaml" 2>&1 || true
oc get svc -n openshift-monitoring -o yaml > "$RUN_DIR/cluster/openshift-monitoring-services.yaml" 2>&1 || true

ROUTE_HOST="$(oc get route web-route -n krkn-ps-fixture -o jsonpath='{.spec.host}' 2>/dev/null || true)"
if [[ -n "$ROUTE_HOST" ]]; then
  curl -ksS -i "http://${ROUTE_HOST}/" > "$RUN_DIR/cluster/route-probe-http.txt" 2>&1 || true
  curl -ksS -i "https://${ROUTE_HOST}/" > "$RUN_DIR/cluster/route-probe-https.txt" 2>&1 || true
fi

conda run -n conda-krkn python -c "from krkn_ai.cli.cmd import main; main()" discover \
  --kubeconfig "$KUBECONFIG_PATH" \
  --namespace krkn-ps-fixture \
  --output "$RUN_DIR/generated/current-discover.yaml" \
  --verbose > "$RUN_DIR/generated/discover-stdout-stderr.txt" 2>&1

YAML_PATH="$RUN_DIR/generated/current-discover.yaml" python - <<'PY' > "$RUN_DIR/generated/parsed-summary.txt"
import os
import yaml

data = yaml.safe_load(open(os.environ["YAML_PATH"]))
print("has_health_checks:", "health_checks" in data)
print("fitness_query:", data.get("fitness_function", {}).get("query"))
print("scenario:", data.get("scenario"))
for ns in data.get("cluster_components", {}).get("namespaces", []):
    print(
        "namespace_summary:",
        ns.get("name"),
        "pods=", len(ns.get("pods", [])),
        "services=", len(ns.get("services", [])),
        "pvcs=", len(ns.get("pvcs", [])),
        "vmis=", len(ns.get("vmis", [])),
    )
PY

cat > "$RUN_DIR/README.md" <<EOF
# OpenShift Cluster Run: ${RUN_ID}

Kubeconfig path used: \`${KUBECONFIG_PATH}\`

Important files:

- \`cluster/routes-full.yaml\` - fixture Route metadata
- \`cluster/openshift-monitoring-routes.yaml\` - OpenShift monitoring Routes / Thanos discovery input
- \`cluster/prometheus-crd.yaml\` - Prometheus CRs, if visible
- \`generated/current-discover.yaml\` - YAML generated by current discover
- \`generated/parsed-summary.txt\` - parsed summary of generated YAML
EOF

echo "Captured OpenShift run: $RUN_DIR"
